### ISSUE TITLE
Web UI settings are not saving

### ISSUE THREAD

**Issue by Jude741** [AronHetLam/ATEM_tally_light_with_ESP8266#103]
I'm using a D1 mini pro and i followed the instructions properly and i have reached til web interface setup. It connects to wifi but apart from ssid and password no other settings are saved. It says “Settings saved successfully” but the settings go back to the default values. Ex: Tally Light name ESP-93A6A8, static IP false and ATEM IP 0.0.0.0 etc. Highly appreciate your support on this matter.

**Comment by Jude741** [comment]
I chose "LOLIN(WEMOS) D1 R2 & mini" in the boards manager instead of "D1 mini pro" and it worked. Thank you for your support.

**Comment by AronHetLam** [comment]
Glad you got it working. 🙂

Did you install it from the web installer before?
If so, I need to figure out a fix for that.

**Comment by AronHetLam** [comment]
If you didn't use the web installer, maybe I could have you test it as I don't have a D1 mini pro?

**Comment by Jude741** [comment]
Sorry for my late response. I used the aduvino IDE to upload the program because i wanted to slightly modify. I haven't tried the web installer.
