### ISSUE TITLE
ATEM Tally Light Design

### ISSUE THREAD

**Issue by Jude741** [AronHetLam/ATEM_tally_light_with_ESP8266#106]
I want to express my gratitude to Aron for this program that inspired my first Arduino project. As someone with no prior experience in C++, I relied on my knowledge of Google Apps Script and a bit of JavaScript. Thanks to resources like YouTube and guidance from ChatGPT, I successfully modified and built my ATEM Tally Light.

In addition to the standard tally LED indications, I incorporated a 3mm LED on Pin 8. This LED flashes when there's no WiFi or switcher connection and remains on when the switcher is connected. This feature helps users quickly determine if the tally light is connected to the switcher, when not in preview or program.

For LED2, I removed the connectivity indicators (White & Pink) to ensure only the camera operator sees them. An ABS plastic box from Amazon, with drilled holes for LEDs and for the antenna, completes the setup.

Feel free to use or modify this design if it suits your environment. Thank you!

ABS Plastic box (61 x 36 x 25 mm)
[https://a.co/d/2KfkqyC]()

![image](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/150415046/dde5e3e5-0092-4218-bda2-5b22a13ccf87)

![image](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/150415046/2b162d2e-2714-448c-99f2-9bd8c8ea4798)

![image](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/150415046/393cd6aa-b33a-4762-b319-91f49757c95f)

![image](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/150415046/c5d4cd8a-328f-4b14-8943-bd75a74ad889)

**Comment by AronHetLam** [comment]
I'm glad to hear it, and your tallies looks awesome. 
Thanks for the great feedback!
