### ISSUE TITLE
card not working

### ISSUE THREAD

**Issue by AlberONE** [AronHetLam/ATEM_tally_light_with_ESP8266#12]
hi, I followed the instructions on mounting the card and after regularly programming the card I tried to see if everything worked. After about an hour of switching on the red LED, the card broke. I thought I had badly powered the card with the 5 volts pin, so I redid the whole sequence on a new one by feeding it with the micro USB. after an hour the new one broke. Do you have any suggestions?

**Comment by AronHetLam** [comment]
Sounds odd. Powering the D1 mini with 5v through the 5v pin is the same as powering it through USB, so unless you accidentally powered it with too much voltage both ways, that's not the issue.

What LED do you use, and how many amps does it draw? Mine draw around 20 mA. The esp8266's pins can't handle much more than that. I even think the datasheet rates them at 12 mA only, however mine are still fine after half a year of weekly usage.

I assume you have used the correct resisors, and that "broke" means that you aren't able to reprogram it or see anything in the serial monitor, and that it isn't just the LED that doesn't work.

**Comment by AronHetLam** [comment]
Maybe you could add a picture of the chip.

**Comment by AlberONE** [comment]
Salve,
Il problema si verifica dopo circa un’ora dall’accensione della luce rossa. Volevo verificare quanto le batterie rendessero autonomo il kit. Quindi ho attivato la luce rossa e dopo un’ora la luce è diventata rosa. Ho provato a riprogrammare la scheda ma non ci sono più riuscito.
Allego il fotografico
Grazie
Alberto

**Comment by AlberONE** [comment]
Hi, 
the issue happens one hour after the red light turns on. I wanted to prove the duration of the battery, so I activated the red light but it turned pink after an hour or so. I tried to program the card again but I didn't managed to. I am attaching a photo. Thank you in advance. Alberto

![IMG_4611](https://user-images.githubusercontent.com/76922159/103546201-ea72e980-4ea2-11eb-942e-d5a3a1de21cd.JPG)
![IMG_4610](https://user-images.githubusercontent.com/76922159/103546228-f199f780-4ea2-11eb-95dd-12625a1b3210.JPG)
![IMG_4609](https://user-images.githubusercontent.com/76922159/103546254-fbbbf600-4ea2-11eb-86ec-d1bc89eef994.JPG)
![IMG_4608](https://user-images.githubusercontent.com/76922159/103546292-09717b80-4ea3-11eb-917e-fde8281a723b.JPG)
![IMG_4606](https://user-images.githubusercontent.com/76922159/103546332-1a21f180-4ea3-11eb-99a7-0c0b90b884b7.JPG)
![IMG_4605](https://user-images.githubusercontent.com/76922159/103546360-260db380-4ea3-11eb-820c-02d0886ca218.JPG)
![IMG_4604](https://user-images.githubusercontent.com/76922159/103546382-3160df00-4ea3-11eb-9307-fc7e11cd133a.JPG)
![IMG_4603](https://user-images.githubusercontent.com/76922159/103546405-39b91a00-4ea3-11eb-8b25-1d3a13668005.JPG)

![IMG_4614](https://user-images.githubusercontent.com/76922159/103546135-d0d1a200-4ea2-11eb-89d8-4ba8d6535c56.JPG)
![IMG_4613](https://user-images.githubusercontent.com/76922159/103546168-daf3a080-4ea2-11eb-810d-d8d470aa463c.JPG)
![IMG_4612](https://user-images.githubusercontent.com/76922159/103546187-e47d0880-4ea2-11eb-8ecc-0bdc0f71f394.JPG)



![IMG_4615](https://user-images.githubusercontent.com/76922159/103546095-c31c1c80-4ea2-11eb-97e4-a57d5692cd50.JPG)

**Comment by AlberONE** [comment]
this is resistors

<img width="1680" alt="Schermata 2021-01-04 alle 15 48 05" src="https://user-images.githubusercontent.com/76922159/103547109-412cf300-4ea4-11eb-9ff4-e7af99336197.png">

**Comment by AronHetLam** [comment]
I assume you closed the issue by accident, so I reopened it 🙂

To me the first message sounded like you fried the chips, but that's not the case. The pink light indicates that it looses the connection to the ATEM. On the settings website the status should reflect that state.

From looking at your pictures it looks loæike you wired it correctly.

Why it would loose it's connection to the ATEM after an hour I don't know. I'd have too look into that once I have time.
Does it reconnect if you turn it off and on?
Did you select the correct COM port and board in board manager when you tried to (re)program it? (COM port can change when you plug it in again)

**Comment by AronHetLam** [comment]
This is what I have selected.
![billede](https://user-images.githubusercontent.com/5564813/103565850-57957780-4ec1-11eb-92eb-a347c2b74dd2.png)

**Comment by jmvb-cl** [comment]
OFF topic quick question!

Can I use the "PRO2 version, with external antenna?

https://www.amazon.com/-/es/D1-Mini-ESP8266-conector-Internet-Desarrollo/dp/B072Q4LHDL

Thank you!

**Comment by AronHetLam** [comment]
@jmvb-cl it should work, just select the correct board before you upload it.

**Comment by jmvb-cl** [comment]
The relay use the ESP01 board, so I guess I should use "Generic ESP8266 module"

This is the pinout

![image](https://user-images.githubusercontent.com/77258813/104318079-aba1ec80-54bd-11eb-85f0-cbad83be21b5.png)
