### ISSUE TITLE
Wt32-eth01 Support

### ISSUE THREAD

**Issue by jmvb-cl** [AronHetLam/ATEM_tally_light_with_ESP8266#122]
I'm looking add to network, a wired tally unit which act like a server, in order to avoid Atem freeze

I found Wt32-eth01, which lack USB port, but I found a USB to UART TTL board to add, so, problem solved I guess

Did anyone used this board?

**Comment by AronHetLam** [comment]
I haven't, but I'm interested to hear about the results if you try it out.

**Comment by jmvb-cl** [comment]
What if instead buy you a coffee, buy you one of those? 
villeg.jm at gmail.com if you are interested..

**Comment by jmvb-cl** [comment]
@AronHetLam you got it?

**Comment by jmvb-cl** [comment]
I want to highlight the incredible, dedicated and selfless work of Aron
He has had the volition and patience to modify the code to make this device possible to work.
This, without counting the good disposition he had with me (and my poor computer skills) to ensure that I could program and operate the WT32
Problem solved!!

**Comment by jmvb-cl** [comment]
I want to highlight the incredible, dedicated and selfless work of Aron
He has had the volition and patience to modify the code to make this device possible to work.
This, without counting the good disposition he had with me (and my poor computer skills) to ensure that I could program and operate the WT32
Problem solved!!

**Comment by jmvb-cl** [comment]
I was doing a few of big show with the tally’s and WT32 and I have a couple of issues

Seems like the WT32 have some limitations managing more than 5 tally at once

3 or 4 is ok, but more than 5, the WT32 lost the ATEM connectivity after a random time to use, and the LED's turn purple.

If I reboot it, resume the functionality for a while until need reboot again.

It is possible in the code add some way to force re reconnection or something like that?

**Comment by jmvb-cl** [comment]
Sometimes, the last connected tally blink purple, and I got this message "Connection rejected - no empty slot"

<img width="580" height="446" alt="Image" src="https://github.com/user-attachments/assets/77e902bd-0af6-4d09-b907-0bdcd223e33e" />

**Comment by jmvb-cl** [comment]
@AronHetLam ?
