### ISSUE TITLE
Feature request: Add an option for led ws2812

### ISSUE THREAD

**Issue by jadiels** [AronHetLam/ATEM_tally_light_with_ESP8266#127]
Would be great to work with this module:

![IMG_4762](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/42808680/d74ab998-3995-48cf-9f8d-b9bb1ef19b6e)

**Comment by AronHetLam** [comment]
There is support for addressable LEDs like that one, but you need to change the pin numbers. In the code pin D7 is used as data pin. Looks like the module on your picture uses D2.
