### ISSUE TITLE
Is it possible to make this work with FOR.A Hanabi HVS 100 Video switcher?

### ISSUE THREAD

**Issue by Jude741** [AronHetLam/ATEM_tally_light_with_ESP8266#130]

**Comment by AronHetLam** [comment]
Sadly no. I'm depending on a 3rd party library that handles the connection to ATEM switchers, which won't work for the HVS-100.

I see that the HVS-100 has a connector specifically for tally signals which I suppose you could read with an ESP or arduino, but that will also require rewriting the code. If you have the technical expertise you could read the values and use my server library to connect the tally lights, but I won't really be able to help much.
