### ISSUE TITLE
Could Not work with D1 Mini Pro

### ISSUE THREAD

**Issue by Budilla2** [AronHetLam/ATEM_tally_light_with_ESP8266#131]
HI All, i tried to use the tally with the d1 mini pro but it cannot be programmed, several chips same problem.

Is there a way to work with D1 mini pro? Has anyone tried and had success?

Thanks for your help
Regards

Marcelo
Brazil

**Comment by jmvb-cl** [comment]
yes, I did success... how are you uploading the code?

**Comment by Budilla2** [comment]
> yes, I did success... how are you uploading the code?

I tried to upload de code using the web installer exactly as i did with the D1 mini, but gives me a message as attached (failed to initialize). I have tried other 2 D1 mini pro and same problem. Maybe i'm doing something wrong.
![Screen Shot 2024-08-30 at 09 01 19](https://github.com/user-attachments/assets/932e7a51-098e-469f-b471-80fbdb10b346)

**Comment by jmvb-cl** [comment]
Seems like driver issue.. do you have parallels in your mac?

**Comment by Budilla2** [comment]
Great! I tried on my son computer with Windows, i have instales the drivers
and boom! It worked!

Thanks for your support!

Em sex., 30 de ago. de 2024 às 21:43, jmvb-cl ***@***.***>
escreveu:
