### ISSUE TITLE
D1 mini pro Board does only work up to FastLED Version 3.6.0

### ISSUE THREAD

**Issue by bilgermoritz** [AronHetLam/ATEM_tally_light_with_ESP8266#136]
We tried to install the code via the Arduino IDE, but the Tally light would not work. We then tried different Versions of the FastLED library and discovered that everything works when we use Version 3.6.0. 

All later versions of FastLED are not working. Not a big problem at all but just a heads up for others having issues with that.

**Comment by AronHetLam** [comment]
This is exactly why I made the web installer and recommend everyone to use that instead of the Arduono IDE.
There are a handful of small but important details to take into account when building it manually. All of those things are taken care of in the web installer 😊
