### ISSUE TITLE
only say thanks

### ISSUE THREAD

**Issue by jmvb-cl** [AronHetLam/ATEM_tally_light_with_ESP8266#14]
Aron, I just wanna says THANK YOU VERY MUCH!!

I only sign in here, just for express my deepest thanks!!

You have no idea what I've been through to get this!
I tried Raspberry (I build successfully a wired one), tried to integrate it RF relays (success, but only one at time, with 2 they interfere) then tried Xbee integration (very complicated, my brain almost blow, I failed miserably), and at the end, the answer was so easy, simple and elegant!

You are the man!! cheers!!

**Comment by AronHetLam** [comment]
Thank you! 
I appreciate your thanks very much, and am happy that the project was easy and useful. That was the goal of it all. 😊
