### ISSUE TITLE
Add "On Air" mode

### ISSUE THREAD

**Issue by AronHetLam** [AronHetLam/ATEM_tally_light_with_ESP8266#15]
Functionality is already added to the repo's ATEMmin lib, and just needs to be implemented in ATEM_tally_light.ino and the settings webpage.

- [x] Add Steaming data parsing to ATEMmin lib
- [x] Document new functionality in ATEMmin lib README and/or in the WIKI
- [x] Add "On Air" option to settings.html
- [x] Add "On Air" mode to ATEM_tally_light.ino
- [x] Add documentation to README and WIKI

**Comment by jmvb-cl** [comment]
What if I don't use the second RGB LED, and instead I connect a red LED in D4?
Would be the same functionality?

**Comment by AronHetLam** [comment]
If you at the moment just put a red LED on D4 you'd only see tally live status for the selected input. As the initial post states, "On Air" mode (whether the ATEM is streaming or not) has not been added to the Arduino code yet.

**Comment by jmvb-cl** [comment]
So, the "on air mode" is about the whole tally lights will have a red light when the streaming is happening?
That is for "atem mini" users, right?

I thought that you were referring to the individual on air lights, thats who the presenter on people in the stage would see, to identify which camera look

![image](https://user-images.githubusercontent.com/77258813/104632949-2e24da80-567d-11eb-8a64-f7ab2d25ac3b.png)

**Comment by AronHetLam** [comment]
The tally lights per individual input (camera) would switch between program and preview - telling the operator whether his cam is output, or about to be output. That's what this project does at the moment, on both LEDs.

"On Air" refers to whether the ATEM is streaming or recording content or not. So yes, as far as i know only the ATEM mini pros supports this. This is the feature this issue is about implementing, so that you use this project as an "On Ari" sign if you wanted too.
