### ISSUE TITLE
What Access Point are you using? Because i cannot reach my ATEM

### ISSUE THREAD

**Issue by Hitower78** [AronHetLam/ATEM_tally_light_with_ESP8266#17]
Hi There

I wonder why "Disconnected - No response from switcher" is in the Status

i am not allone with that "wireless problem to ATEM or Blackmagic Products"
https://forum.blackmagicdesign.com/viewtopic.php?f=4&t=28383

So i am asking those who use this ESP Tally: 
What Access Point is ok?

i use the TP-Link WR841N. Everything works (Cable), but no wireless ATEM Controll (doublecheck IPs, Subnet, Gateway, Ping, Software...)

Thanks for Help :-)

**Comment by AronHetLam** [comment]
I have ubiquity network gear from where I use it, but you should be able to get it to work with any router, really.. However, take a look at this issue #9 - Also someone trying to use a TP-link without success. We sadly didn't find out why.

**Comment by AronHetLam** [comment]
Just skimmed through issue #9 again. If you've tried the steps in there and have the same results, I don't know how to solve it. In your case I would contact TP-link support, and describe the issue. I don't see what should block it. Especially not if you are able to ping the ATEM over WiFi from your PC.

I have read about some cases where it helped changing the IP settings over USB on the ATEM from eg static to DHCP and vice versa. Sometimes it seems they are broken. In my setup I've given the ATEM a static IP/lease in my router config, outside the DHCP range. At the moment I don't remember if I set the ATEM's IP settings are static or not. Probably static, but I'd have to double check.

**Comment by jmvb-cl** [comment]
I have a TL-WR740N in my system

Tomorrow I'll take some screen captures of my configuration...

BTW, I don't know if I made some changes before, but my ATEM IP is 192.168.10.239...

Can you control your ATEM with your PC connected by wifi?

**Comment by Hitower78** [comment]
Hi there
I check now my 2nd Accespoint: its a TP-Link TL-WA901. 
The Same: 
when i use any wireless Device (Notebook, Iphone or the Tally) and try to connect to the ATEM it doesnt work. 
No Ping, no Connection with ATEM Software
Other Stuff (companion to vmix tally) is running on both Access Points

I will try another one

**Comment by AronHetLam** [comment]
Yes, i can access my ATEM via software control over WiFi. If you can't you have an issue with you network... #9 was the same problem, where at the end he switched to another router/AP, which solved it for him. I really don't know why some routers blocks the ATEM traffic  from ethernet to WiFi. I recommend contacting TP-link, with a description of what steps you have taken, and that you can access it over ethernet, and not WiFi.

Are you able to ping the ATEM over both WiFi and ethernet? And is it different when you enable/disable client isolation and likewise settings? If you can ping it over WiFi, but not connect to it with software control, that's what I would tell TP-link, and ask them why and how to solve. 😊

**Comment by jmvb-cl** [comment]
![Captura de Pantalla 2021-01-19 a la(s) 10 27 32](https://user-images.githubusercontent.com/77258813/105041519-d9e57600-5a41-11eb-8a2d-a97998a411d4.png)
![Captura de Pantalla 2021-01-19 a la(s) 10 27 41](https://user-images.githubusercontent.com/77258813/105041576-ea95ec00-5a41-11eb-9d6b-334adf1f3609.png)
<img width="1115" alt="Captura de Pantalla 2021-01-19 a la(s) 10 27 51" src="https://user-images.githubusercontent.com/77258813/105041605-f5508100-5a41-11eb-8463-8eb145dd7b8b.png">
<img width="1113" alt="Captura de Pantalla 2021-01-19 a la(s) 10 27 58" src="https://user-images.githubusercontent.com/77258813/105041629-fd102580-5a41-11eb-8662-c2472de9aa5b.png">
<img width="1129" alt="Captura de Pantalla 2021-01-19 a la(s) 10 28 11" src="https://user-images.githubusercontent.com/77258813/105041695-11ecb900-5a42-11eb-93a4-88e8f302621c.png">
<img width="1119" alt="Captura de Pantalla 2021-01-19 a la(s) 10 28 28" src="https://user-images.githubusercontent.com/77258813/105041724-1c0eb780-5a42-11eb-8e49-27d7b3da3a11.png">

**Comment by Hitower78** [comment]
Hi
Thanks for your answer.
No Ping with wireless Connection on both of that Access Point to the ATEM. 
So No wireless Control. 

I didnt understand that because the rest over years is still running over years with that APs 
(Ipads to companion, Notebooks, Iphones, Widget designer and so on) 

There is no Isolation and other Settings. i think the most settings are default (i only change ssid, dhcp settings and IP)

Perhaps the 3rd AP will work. 

Thanks for your Pictures. There are the same settings on the first AP (841), i will check the other later

**Comment by Hitower78** [comment]
And finally it works!
A "Good" Access Point is the Key. The LANCON is so powerful and there are so many Settings...
i need 10min for the easy Hotspot settings :-P

Thanks all! I think this Topic is ready to close :-)

Greetings from Hamburg / Germany
Daniel

**Comment by AronHetLam** [comment]
To me the settings looks good, so again, I don't know what causes the problems..
Good you found a solution.
I'll close this ☺
