### ISSUE TITLE
D1 Mini pro (with external antenna) won't set camera other than #1

### ISSUE THREAD

**Issue by jmvb-cl** [AronHetLam/ATEM_tally_light_with_ESP8266#18]
Just received a new D1 mini pro (in order to increase the wifi reception)

Downloaded the CP210x USB driver

Choose LOLIN (WEMOS)D1 mini pro in boards

Upload the sketch as usual, flawlessly

Set the tally as usual, flawlessly

Here the odd things begin..

No matter which camera I selected, at the end, always the #1 is set.

I re-do the set more than 10 times, and no changes.

BUT, If the LOLIN (WEMOS) R1&R2 is selected in the board menu, the set-up finally can be done

So, be advice, if the Mini pro is used, select LOLIN (WEMOS) R1&R2

**Comment by jmvb-cl** [comment]
OFF TOPIC; Just see a closed issue about the ATEM 1 M/E Production Studio 4K
I have this switch and I used the tally since the day I discover it.
So, if the user who report had a problem, that was not the previous version.

**Comment by AronHetLam** [comment]
@jmvb-cl Odd, doesn't the production 4k have 21 inputs? (I only have a mini pro, so the rest is pure speculation and guessing for me 😉)

Btw, you can still comment on a closed issue 🙂

**Comment by jmvb-cl** [comment]
Nope, the ATEM 1 M/E have 10 inputs,,

![image](https://user-images.githubusercontent.com/77258813/106358734-beedee00-62ec-11eb-9565-1de6d63341e0.png)

The ATEM 2 M/E have 20 (input 1 is HDMI or SDI switchable)

![image](https://user-images.githubusercontent.com/77258813/106358764-ecd33280-62ec-11eb-8b7b-9a9417dfaa6c.png)


PDT: my bad... can you move this to there?

**Comment by AronHetLam** [comment]
I must have misread 21 (20 active) inputs for the 2 m/e as the 21 inputs i talked about. However, there are models with 40 inputs, so the fix is still relevant for those cases.

If @alexcruz still has a problem with his setup, I'd have to look into that. If you have the same swithcer as he has, maybe you know something @jmvb-cl?

I might be able to quote these posts in issue #9

**Comment by jmvb-cl** [comment]
I just follow your instructions and all was perfect

**Comment by AronHetLam** [comment]
As this isn't really an issue I can dommuch about I'll close it here.

Others can still find it. 🙂
