### ISSUE TITLE
Program mode not working.

### ISSUE THREAD

**Issue by Shaver443** [AronHetLam/ATEM_tally_light_with_ESP8266#2]
When I go to enter the program mode the lights turn off. When I put the camera in the preview they turn red.
I've re-uploaded the sketch multiple times. 

Anything I'm missing?

**Comment by AronHetLam** [comment]
You might have selected the incorrect board in Arduino - double check with the guide.

**Comment by AronHetLam** [comment]
Let me know if you get it working. Then I can close this issue. 🙂

**Comment by Shaver443** [comment]
That was it!!! Thank you so much!

**Comment by AronHetLam** [comment]
You're welcome 🙂
