### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by tcgerhard** [AronHetLam/ATEM_tally_light_with_ESP8266#21]
Aron, great project.   In the process of setting up six tally lights, and making some customizations along the way, possibly with some future PRs (support common Anode LEDs, have LED2 indicate status of a different camera than LED1).
I've forked your repo and started to make my changes, but I see that the .ino files comes with CRLF line endings, which automatically get removed by the Arduino IDE when I save files on my Mac; this leads to the entire file showing up as changing on checkin.
Somewhat of a novice on github -- my understanding is that github stores text files internally with LF and converts as needed on fetch, but this file (at least) seems to be stored with CRLF.   Do you have any suggestions?   I'm holding off on any changes until I sort this out...

**Comment by AronHetLam** [comment]
Thanks for the positive feedback. I appreciate it. 🙂

It seems most line endings where `CRLF,` at least the files I added myself. I hadn't thought of line endings until now. Git can handle them automatically, but you need to tell it to, either in global or repository configuration. I added `.gitattributes`, and normalized all the files to `LF`. Hopefully that should've solved it. 🙂
