### ISSUE TITLE
LED 2 for second ATEM input

### ISSUE THREAD

**Issue by frabusas** [AronHetLam/ATEM_tally_light_with_ESP8266#22]
Could LED2 be set to another ATEM input?
I would like to show the speaker which of two cameras is currently in the programme and would then only need a D1 mini.

**Comment by AronHetLam** [comment]
Yes, but it's not possible change through the website (yet...), however, I could guide you to the code you'd need to change. It would require two places where you'd replace two words with a number instead.

**Comment by frabusas** [comment]
great, can you tell me how and where I would have to adapt the code? Perhaps a screenshot?

**Comment by AronHetLam** [comment]
Depending on if you want to change the first or the second LED you'd swap out the orange or the green ones. You'd swap `settings.tallyNo` with the input number minus one. So if you want it to show tally light for input 1 on the switcher, you'd put 0 (zero) in the parentheses.
![billede](https://user-images.githubusercontent.com/5564813/109150866-b9f45100-7769-11eb-979b-5cd0ef260ee9.png)
You can search for `//set tally light` to quickly navigate to the relevant code be pressing `Ctr + f`.
If you only swap one of them you can still set the other one in the website, if you swap both, the settings from the website are ignored.

Good luck! 😊

**Comment by frabusas** [comment]
Great, that works - thanks for the quick support
