### ISSUE TITLE
V3.1 can not compile code

### ISSUE THREAD

**Issue by goudi76** [AronHetLam/ATEM_tally_light_with_ESP8266#27]
Hy
I get this error when I try to compile the code.
Do I miss an library?

![Bildschirmfoto 2021-03-13 um 20 07 55](https://user-images.githubusercontent.com/78760087/111041407-50966280-8438-11eb-98ad-d578c4d6a58a.png)

I hope you can help me to solve this problem
And many thanks for your support and Work!!!

**Comment by goudi76** [comment]
if I uncommand line 536, 541, 543 it works...

**Comment by goudi76** [comment]
Line 537 is also buggy I have uncommand it as well for testing

**Comment by AronHetLam** [comment]
My fault - It didn't merge correctly.
It's now been fixed 😅
