### ISSUE TITLE
something confilct about  define led2

### ISSUE THREAD

**Issue by fareign** [AronHetLam/ATEM_tally_light_with_ESP8266#32]
LED2 define D4, will light up the board blue led.

**Comment by goudi76** [comment]
The internal LED is on D4 Pin. 

If the output of D4 is high, the onboard LED is lighting.

**Comment by AronHetLam** [comment]
Yes, as @goudi76 says, the built-in led is connected to D4. However, it will light when D4 is low, which is why it's off when led 2 is red, and on when it's not.
You can see that
```C++
Serial.println(LED_BUILTIN);
Serial.println(D4);
```
both will print `2` in the console, referencing the same pin.
