### ISSUE TITLE
[Question] Is ATEM v8.6 supported?

### ISSUE THREAD

**Issue by CeDoMain** [AronHetLam/ATEM_tally_light_with_ESP8266#39]
Hello Aron,

do you know if the ATEM Library from Skaarhoj can receive tally information from the actual version 8.6? I know that Skaarhoj says that the free version of his lib only supports up to 7.5.0 but is this true for all aspects of the lib?

We have an updated mixer and before i build the whole system up i want to know if this can word.

Thanks for your reply,
Cedric

**Comment by AronHetLam** [comment]
Yes, they still work. They just don't have the latest features implemented. In my version of them you'll find that I added a few things, which is documented in the wiki.
