### ISSUE TITLE
Won't compile NodeMCU 1.0

### ISSUE THREAD

**Issue by Andrej65416das** [AronHetLam/ATEM_tally_light_with_ESP8266#40]
# Hi, 
#### I'm trying to load the code into NodeMCU 1.0, which still shows me an error, I know that you have already solved this problem, but you have not solved it, so I am also sending a detailed statement from the console.

You will find a statement in this file: [eror.txt](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/files/6336723/eror.txt)

### **Thanks**

**Comment by AronHetLam** [comment]
I looked into it, and found that the PIN definitions are a bit different on the NodeMCU. If you remove the ´D´ from ´D7´ on line 100 so it becomes ´#define DATA_PIN    7´ it should work. I get to compile.

**Comment by Andrej65416das** [comment]
@AronHetLam It's already working, thanks

**Comment by AronHetLam** [comment]
Found what seems to be a proper fix, could I have you test the latest commit cd1ad2af30040fad512d64e0350d886dcc503ebb, and see if that works too? It should check if you are compiling it for the NodeMCU.
If it works I'll put it in a release.

**Comment by Andrej65416das** [comment]
Hi, I changed the code, and it worked for me when I compiled it.

Thanks for solving the problem
