### ISSUE TITLE
First Project with Tally Light

### ISSUE THREAD

**Issue by Stephan-Kl** [AronHetLam/ATEM_tally_light_with_ESP8266#42]
Hello,
last week I had my first project with the tally light added to my setup and I can say it worked perfect. I have build three of them for a live stream event, added a small 5V wifi-router which I connected directly to the ATEM. This time we had no problem with the anchorman to choose the right camera.

Thanks allot :)

![Tally_1](https://user-images.githubusercontent.com/64946253/115983300-ac5c1b80-a5a0-11eb-97b9-732314705e10.jpg)
![Tally_2](https://user-images.githubusercontent.com/64946253/115983303-b1b96600-a5a0-11eb-9dc8-3003d3578c6f.jpg)
![Tally_3](https://user-images.githubusercontent.com/64946253/115983308-b67e1a00-a5a0-11eb-8ecb-985e0a392404.JPG)

**Comment by AronHetLam** [comment]
Looks awesome! 😊
