### ISSUE TITLE
Error while uploading: no headers files (.h) found in C:\Users\Gert\Documents\Arduino\libraries\ATEM

### ISSUE THREAD

**Issue by Zaktindegeute** [AronHetLam/ATEM_tally_light_with_ESP8266#50]
Who can help? I'm an complete 'newbee' to this and just made my first steps... ;-)

During upload i got this error message, what can i do ?

Regards Gert

Arduino:1.8.15 (Windows 10), Board:"LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), v2 Higher Bandwidth, Disabled, None, Only Sketch, 921600"

ATEM_tally_light:35:10: fatal error: ATEMmin.h: No such file or directory

   35 | #include <ATEMmin.h>

      |          ^~~~~~~~~~~

compilation terminated.

exit status 1

ATEMmin.h: No such file or directory

Ongeldige bibliotheek gevonden in C:\Users\Gert\Documents\Arduino\libraries\ATEM: no headers files (.h) found in C:\Users\Gert\Documents\Arduino\libraries\ATEM

Ongeldige bibliotheek gevonden in C:\Users\Gert\Documents\Arduino\libraries\ATEM_tally_light: no headers files (.h) found in C:\Users\Gert\Documents\Arduino\libraries\ATEM_tally_light

Ongeldige bibliotheek gevonden in C:\Users\Gert\Documents\Arduino\libraries\ATEM_tally_test_server: no headers files (.h) found in C:\Users\Gert\Documents\Arduino\libraries\ATEM_tally_test_server

Ongeldige bibliotheek gevonden in C:\Users\Gert\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\Gert\Documents\Arduino\libraries\libraries

Ongeldige bibliotheek gevonden in C:\Users\Gert\Documents\Arduino\libraries\Wiki: no headers files (.h) found in C:\Users\Gert\Documents\Arduino\libraries\Wiki

**Comment by AronHetLam** [comment]
Hi

Looks like you have copied the the downloaded files over incorrectly, and therefore it's unable to find them.
You need to copy the `libraries` folder from the download directly into the `Arduino` folder.

Right now it looks like this in your system:
`C:\Users\Gert\Documents\Arduino\libraries\libraries`

But it needs to look like this:
`C:\Users\Gert\Documents\Arduino\libraries`

I hope that makes sense 🙂
