### ISSUE TITLE
10mm RGB LED brightness not enough

### ISSUE THREAD

**Issue by aexeler** [AronHetLam/ATEM_tally_light_with_ESP8266#52]
Hello,
i use the Tally Light with a 10mm RGB-LED, but outside i cant see the Colour of the LED.
Can i use a other LED (more Power, brightness) or a 0.96 OLED I2C Display with background Colour and a Text in the Display?
for example
"Ready and OnAir"?

Greets
Andreas

**Comment by AronHetLam** [comment]
You should easily be able to use brighter LEDs, but you have to think about how much current they draw.
If you use addressable LEDs such as neopixels you could power them externally. Neopixels are supported.
You can use a display, but you'd have to code it yourself.

**Comment by AronHetLam** [comment]
I'll close this as the main question is answered.
