### ISSUE TITLE
ESP Wifi SSID Storage

### ISSUE THREAD

**Issue by paulkilroy** [AronHetLam/ATEM_tally_light_with_ESP8266#56]
The WIFI.begin() is not saving the wifi SSID and Password on the heltec esp32 dev board.. Not sure why because their demos work.  It must be a library or header issue.

**Comment by paulkilroy** [comment]
Yes - It was getting in that code.. There were a few issues with the underlying ESP32 WiFi code to work around. Turning on verbose logging helped see a lot of extra stuff going on and out of sequence things.

1- calls to WiFi.persistent( false ) and then to true were not necessary. According to the documentation the ESP will not update the SSID/PSK in EEPROM as long as they do not change.  The setting back and forth confused the ESP32 code and it would not save for some reason. I didn't look that deep, but removing the calls to WiFi.persistent(false) fixed things

2- Using AP_STA mode confused the ESP32 especially with AutoReconnect set to true. This caused delays in connecting to the AP, serving web pages and saving -- maybe other things as well. Now connecting to the AP and config page is face and reliable.

3- I needed to add a few delay()s in the saving code to get the ESP32 to switch over from AP mode to STA mode during the save. To compensate, I trimmed down the existing 4 second save and added a server.close() before it which flushed the connection (at least on the ESP32)

You code is awesome, and very easy to walk though. Thanks for making this available to the public! Let me know if this doesn't work on your ESP, my email is my git account on gmail if you want to chat directly.


`--- /tmp/o	2021-10-30 18:18:03.000000000 -0500
+++ ATEM_tally_light.ino	2021-10-30 18:27:51.000000000 -0500
@@ -169,10 +169,14 @@
     Serial.println("########################");
     Serial.println("Serial started");
 
+    //save flash memory from being written too without need.
+    //WiFi.persistent(false); // PSK Per the ESP documentation, flash will only be written to if the WiFi parameters change.. Its ok to leave on
+
     //Read settings from EEPROM. Settings struct takes 72 bytes total (according to sizeof()). WIFI settings are stored seperately by the ESP
-    EEPROM.begin(72); //Needed on ESP8266 module, as EEPROM lib works a bit differently than on a regular arduino
+    EEPROM.begin(sizeof(settings)); //Needed on ESP8266 module, as EEPROM lib works a bit differently than on a regular arduino
     EEPROM.get(0, settings);
 
+
     //Initialize LED strip
     if (0 < settings.neopixelsAmount && settings.neopixelsAmount <= 1000) {
         leds = new CRGB[settings.neopixelsAmount];
@@ -205,9 +209,9 @@
     FastLED.show();
 
     Serial.println(settings.tallyName);
-    //Serial.println(sizeof(settings)); //Check size of settings struct
 
-    WiFi.persistent(false);
+    // PSK WiFi.persistent(false); // PSK Per the ESP documentation, flash will only be written to if the WiFi parameters change.. Its ok to leave on
+
     if (settings.staticIP) {
         WiFi.config(settings.tallyIP, settings.tallyGateway, settings.tallySubnetMask);
     }
@@ -256,7 +260,9 @@
             } else if (firstRun) {
                 firstRun = false;
                 Serial.println("Unable to connect. Serving \"Tally Light setup\" WiFi for configuration, while still trying to connect...");
-                WiFi.mode(WIFI_AP_STA); // Enable softAP to access web interface in case of no WiFi
+                // PSK WiFi.mode(WIFI_AP_STA); // Enabling both AP and STA mode at the same time WITH AutoReconnect() caused a ton of errors and time 
+                // PSK consuming code deep in the ESP32 code, changing to just AP served and process the config page must faster while in AP mode
+                WiFi.mode(WIFI_AP); // Just use as AP until someone connects to the webpage and submits, then change to WIFI_STA
                 WiFi.softAP("Tally Light setup");
                 setBothLEDs(LED_WHITE);
                 setStatusLED(LED_WHITE);
@@ -341,6 +347,8 @@
 
     //Handle web interface
     server.handleClient();
+
+    delay(100);
 }
 
 //Handle the change of states in the program
@@ -740,14 +751,20 @@
 
             server.send(200, "text/html", (String)"<!DOCTYPE html><html><head><meta charset=\"ASCII\"><meta name=\"viewport\"content=\"width=device-width, initial-scale=1.0\"><title>Tally Light setup</title></head><body><table bgcolor=\"#777777\"border=\"0\"width=\"100%\"cellpadding=\"1\"style=\"font-family:Verdana;color:#ffffff;font-size:.8em;\"><tr><td><h1>&nbsp;Tally Light setup</h1></td></tr></table><br>Settings saved successfully.</body></html>");
 
-            //Delay to let data be saved, and the responce to be sent properly to the client
-            delay(5000);
+            // Delay to let data be saved, and the response to be sent properly to the client
+            server.close(); // PSK Close allowed me to ensure the response got to the client and take the delay down from 5000 ms to 100 ms
+            delay(100);
+
+            // Change from AP mode into STA mode to try to connect to your router
+            WiFi.mode(WIFI_STA); // Disable softAP if connection is successful
+            delay(100); // Give it time to switch over to STA mode (this is important on the ESP32 at least
 
-            if (ssid && pwd && (ssid != getSSID() || pwd != WiFi.psk())) {
-                WiFi.persistent(true);
-                WiFi.begin(ssid.c_str(), pwd.c_str());
+            if (ssid && pwd) {
+                // PSK Pass in false so we don't waste time trying to connect, just save the new SSID/PSK
+                wl_status_t status = WiFi.begin(ssid.c_str(), pwd.c_str(),false);
             }
 
+            delay(100);
             ESP.restart();
         }
     }`

**Comment by AronHetLam** [comment]
Sorry for taking such a long time to get back. I'm quite busy at the moment. However, thanks a lot for your work! 🙂

1. Interesting that it breaks things. That doesn't make sense to me. I kept it in when I initially created the project, as I didn't find conclusive information about it at the time. But it makes sense to remove it.

2. I assume it can't auto reconnect when in AP only mode? I do want it to auto reconnect if it loses WiFi connection for whatever reason. Having to reconnect to the AP or reboot it if it loses connection would be a bad experience compared to auto reconnect.
    Maybe it could be set up to go into AP only/config mode if it fails to connect on the first try after a reboot. Thereafter it could either do as it does now, or just not create an AP at all until next reboot.

3. I'm a bit hesitant towards the delay in the main loop() as the `atemSwitcher.runLoop();` method needs to be run frequently enough. I don't have access to a switcher currently, so it'd be a couple of days at least before I can test the code on an ESP8266 with an actual ATEM device.

_Originally posted by @AronHetLam in https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/issues/58#issuecomment-976811737_

<br>
<br>

I got to do a little bit of testing on my ESP8266, and did a few findings.

Latest version of board manager for ESP8266 requires `WiFi.persistent(true)` as it's now disabled by default. See [here](https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/generic-class.html?#persistent)

Also, for both ESP8266 and ESP32 i found that false should be the 5th argument to stop `WiFi.begin()` from connecting. See `begin` for [ESP8266](https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/station-class.html#begin) and [ESP32](https://docs.espressif.com/projects/arduino-esp32/en/latest/api/wifi.html#begin)

_Originally posted by @AronHetLam in https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/issues/58#issuecomment-977219263_

<br>
<br>

I made an [iss56](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/tree/iss56) branch in my own repo based on yours, where I fixed it for the ESP8266 again according to my findings above.

**Comment by AronHetLam** [comment]
Found out I actually have an ESP32 🤦‍♂️

WiFi connection and storage is tested with the commit above on both ESP8266 and ESP32 with erased flash. It worked well on both, with a few partial loads of the setup page on the ESP8266, and none on ESP32. 100 ms delay in the main loop almost seemed to result in more partial loads of the page on the ESP8266, so I'm still not convinced it should be there.

**Comment by paulkilroy** [comment]
#3 - The delay in the main loop was an oversight. My apologies. It was there for the joystick code I'm adding and inadvertently left in this branch, and I see what you're saying about the ATEM code not wanting any kind of delay. I'll rethink how I'm coding that, but in the mean time you can remove it.

#2 You are right about what happens if wifi is dropped, I noticed that after I submitted the patch, the code defaults going back into just AP mode, so it will never reconnect to your wifi.. I can change the block of code back to:
`
 } else if (firstRun) {
                firstRun = false;
                Serial.println("Unable to connect. Serving \"Tally Light setup\" WiFi for configuration, while still trying to connect...");
                WiFi.mode(WIFI_AP_STA); // Enable both AP and STA mode until someone connects to the webpage and submits, then change to WIFI_STA
                WiFi.softAP("Tally Light setup");
                setBothLEDs(LED_WHITE);
                setStatusLED(LED_WHITE);
            }
`
And it seems to work better now.

Regarding passing "false" to the connect function.  I tried that but didn't see any effect, its probably best to have it there though.

Thanks for taking a look at this code.. The joystick stuff is almost ready

**Comment by AronHetLam** [comment]
Tip: If you have more than one line of code use three ` ``` ` before and after. (I edited your comment 🙂).

2 and 3 are fixed in the iss56 branch i have in my repo. I'll merge it into my master and make a new release sometime soon.

Passing `false` as 3rd argument is the same as passing `0`, so it didn't change it from it's default.
