### ISSUE TITLE
Firmware ATEM

### ISSUE THREAD

**Issue by gliepins** [AronHetLam/ATEM_tally_light_with_ESP8266#6]
Dear friend,
I am now testing this setup as you described. However Im getting no connection to the switcher. Before I dig deeper, I found that Skaarhoi librarys only support models firmware below 7.5. Current one is 8.5.
https://www.skaarhoj.com/fileadmin/BMDPROTOCOL.html (red part)
DO you have any comment on that?

Thanks!

**Comment by AronHetLam** [comment]
I know, but it's not an issue.
The libraries just don't support features newer that 7.5.
Tally still works, and I'm pretty sure everything else documented on his site is still functional. I made this project after that was the case 🙂

I manually added the ability to see whether it's streaming or not, so if you're missing something you can add it manually if you know how to.

**Comment by AronHetLam** [comment]
It sounds like you managed to program it. Probably you have an issue in your network setup.
Are you able to connect to the switcher with software control over WiFi? The tally lights connect the same way as software control does.

**Comment by gliepins** [comment]
Alright.. Then we must find the problem. I connected everything, all sides are pinging, but it says : Disconnected - No response from switcher.

**Comment by AronHetLam** [comment]
I don't have enough information about your setup.
Maybe a screenshot of the setup page and the devices' IP addresses can help me find the problem.

Also did you try to connect to the switcher with software control over WiFi?

**Comment by gliepins** [comment]
I will later tonight post pics and setup. I really want to get this thing going! 
But now - what do you mean by software control?

**Comment by AronHetLam** [comment]
Atem software control. The program that lets control you Atem switcher from your pc.

**Comment by gliepins** [comment]
I will later tonight. Yes, i opened control center. All good with ip addresses. All sides are pingng eachother.

**Comment by AronHetLam** [comment]
What do you mean with all sides are pinging each other?

**Comment by gliepins** [comment]
Means that network is working. 
Atem switch up
Arduino up
Pc with Atem soft up

**Comment by gliepins** [comment]
Not arduino but esp8266 chip with led. Sory

**Comment by AronHetLam** [comment]
Ok, must be a network configuration problem then. If it's on the same network and has the correct switcher IP address it should connect automatically.
Sometimes routers makes wired and and WiFi two separated networks, which is why I want you to connect to you switcher with software control over WiFi, to see if that could be the issue.

**Comment by gliepins** [comment]
HI, here are some pics. Ask anything, hoping for your help!
![IMG_3305](https://user-images.githubusercontent.com/26112780/96690971-029b9800-138d-11eb-8f06-26e2ad0e9cf5.JPG)
![IMG_3302](https://user-images.githubusercontent.com/26112780/96690980-04655b80-138d-11eb-9ee9-b316338e19e7.JPG)
![IMG_3303](https://user-images.githubusercontent.com/26112780/96690985-05968880-138d-11eb-9270-806c3cac3c64.JPG)
![IMG_3304](https://user-images.githubusercontent.com/26112780/96690993-07f8e280-138d-11eb-96a5-50c23e7b89e4.JPG)

**Comment by AronHetLam** [comment]
That all looks good. All i can think of is that it might be an issue with the latest version. 
Try with v2.0, and let me know if that changes anything:
https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/releases/tag/v2.0

**Comment by gliepins** [comment]
Wait! I started to notice strange behaviour with the switcher and the network. It does not obtain ip from the dhcp server. It could be the switcher causing problems. I will get to the bottom of it. Stand by :)

**Comment by AronHetLam** [comment]
Static IP addresses will probably help

**Comment by gliepins** [comment]
WORKING!! 
Thank you very much! 
In situations like these it is important to rely on solid knowledge of things before messing with matters I 'm not sure of!

**Comment by AronHetLam** [comment]
What was the problem, and how did you solve it?

**Comment by gliepins** [comment]
Yes, I solved it! Problem was in the Atem switcher having some bogous ip settings. At first it was static ip and I didn't change it. It seemed ok because subnet was correct and it was pinging alright. But when switched Atem over to dhcp, it updated/flushed its ip settings and started to work!

**Comment by gliepins** [comment]
What exactly this setting does? 
![Screenshot 2020-10-21 at 13 14 52](https://user-images.githubusercontent.com/26112780/96706646-852d5300-139f-11eb-86ac-d52ecdbe89ef.png)

**Comment by AronHetLam** [comment]
Ok, cool.

The setting is described here:
https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266#modes-of-operation

You can try them out and see which one fits your use case.

**Comment by gliepins** [comment]
Got it!
Another Q! When in preview, esp LED (not tally LED) glows blue all the time. When in program, it does not glow.
Anything worth knowing here? 
![IMG_3308](https://user-images.githubusercontent.com/26112780/96708183-88c1d980-13a1-11eb-9fc6-0378d0d4a715.JPG)
![IMG_3309](https://user-images.githubusercontent.com/26112780/96708205-911a1480-13a1-11eb-89c3-3e3129946623.JPG)

**Comment by AronHetLam** [comment]
It's connected to the red pin of the second LED as I remember, but inverted signal. I find it useful for showing it has power, if eg. the LED is off.

**Comment by gliepins** [comment]
I see! My concern only was if it indicates some unwanted mode or traffic which could impact power consumption, that's all.
Thanks!
