### ISSUE TITLE
neopixel first led problem

### ISSUE THREAD

**Issue by MitjaCer** [AronHetLam/ATEM_tally_light_with_ESP8266#60]
Hi, i use ws2811 led strip (12led strip)  and the first led it's blinking yellow color. I use Neopixel status LED: None. What can i do?
Thank you

**Comment by MitjaCer** [comment]
Solved: I reloaded the program.

**Comment by AronHetLam** [comment]
Take a look at this post https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/issues/49#issuecomment-899521237 if you run into the problem again.

**Comment by MitjaCer** [comment]
Thank you man!

Il giorno mar 23 nov 2021 alle ore 17:00 Aron het Lam <
***@***.***> ha scritto:
