### ISSUE TITLE
Unable to connect to network 

### ISSUE THREAD

**Issue by HAJLIN** [AronHetLam/ATEM_tally_light_with_ESP8266#66]
For some reason I cannot connect to the unit via network.
After setting router name and password , the light on the unit behangers from white to bleu and finally to purple. Connection is terminated although only a few meters to the access point.
after reinstalling the software, all setup data are still present except for the password.
Has anyone encountered similar problem? All suggestions are welcome.

**Comment by AronHetLam** [comment]
It saves the password, but doesn't send it out to the webpage/show it if you're accessing it via the setup network. Just to make it a little harder to get a password out of it ;)
Is it an ESP8266? Should connect to the network no problem, and the fact that it turns purple tells me it does get onto the wifi. Purple means it's trying to connect to the switcher.

**Comment by AronHetLam** [comment]
Aha, so once it's connected to the network you have to access it through it's IP address on the network. Which is most likely not 192.168.4.1.

You can see the IP if you open the serial monitor in the Arduino IDE (button in top right), if you reset it while it's connected with usb. Or you can give it a static IP address in the setup page.

**Comment by HAJLIN** [comment]
Thanks a lot Aron.
