### ISSUE TITLE
how to fix this errors?

### ISSUE THREAD

**Issue by aalmadusanka** [AronHetLam/ATEM_tally_light_with_ESP8266#69]
n file included from C:\Users\ThinkVishon\Documents\Arduino\libraries\FastLED\src/FastLED.h:67,
                 from C:\Users\ThinkVishon\Documents\Arduino\ATEM_tally_light_with_ESP8266-master\ATEM_tally_light_with_ESP8266-master\ATEM_tally_test_server\ATEM_tally_test_server.ino:35:
C:\Users\ThinkVishon\Documents\Arduino\libraries\FastLED\src/fastspi.h:145:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  145 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Executable segment sizes:
ICACHE : 32768           - flash instruction cache 
IROM   : 284564          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 28325   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 
DATA   : 1504  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 8496  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26400 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 322889 bytes (30%) of program storage space. Maximum is 1044464 bytes.
Global variables use 36400 bytes (44%) of dynamic memory, leaving 45520 bytes for local variables. Maximum is 81920 bytes.
esptool.py v3.0
Serial port COM4
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: c4:5b:be:6c:b3:1a
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 327040 bytes to 233978...
Writing at 0x00000000... (6 %)
Writing at 0x00004000... (13 %)
Writing at 0x00008000... (20 %)
Writing at 0x0000c000... (26 %)
Writing at 0x00010000... (33 %)
Writing at 0x00014000... (40 %)
Writing at 0x00018000... (46 %)
Writing at 0x0001c000... (53 %)
Writing at 0x00020000... (60 %)
Writing at 0x00024000... (66 %)
Writing at 0x00028000... (73 %)
Writing at 0x0002c000... (80 %)
Writing at 0x00030000... (86 %)
Writing at 0x00034000... (93 %)
Writing at 0x00038000... (100 %)
Wrote 327040 bytes (233978 compressed) at 0x00000000 in 5.5 seconds (effective 476.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**Comment by AronHetLam** [comment]
Theese doesnt look like errors. That's just what it outputs while compiling and programming. It looks like it reached 100%, so it should work.

Doesn't it?

**Comment by aalmadusanka** [comment]
What is this massage? 
145 | # pragma message "No hardware SPI pins defined. All SPI access will default to bitbanged output"

**Comment by AronHetLam** [comment]
It's the FastLED library informing you that it's bitbabnging output instead of using hardware SPI, because it's not available on the chip.

It's normal, and you can ignore it. 🙂

**Comment by AronHetLam** [comment]
If you are using addressable LEDs you may need to downgrade the board manager to below version 3.x.x. (so the latest 2.x.x), as it introduced some issues to FastLEDs bitbabnging.

**Comment by aalmadusanka** [comment]
thank you very much for your support

**Comment by AronHetLam** [comment]
You're welcome
