### ISSUE TITLE
LED2

### ISSUE THREAD

**Issue by maf-o** [AronHetLam/ATEM_tally_light_with_ESP8266#7]
Hello, in Wiki on the screenshot of the settings you can read as described in readme for LED2, but only in Wiki there is LED2 mentioned as later implemented in project.
Can you tell what this LED2 does?
I only found in .ino that it might be something atem tellys have.

**Comment by AronHetLam** [comment]
The 2ndLED is just so that you can have 2 LEDs on the same ESP8266. Eg. one facing the camera operator in "normal" mode, and one facing the stage in "program only" mode. 
You can leave the 2nd LED out if you don't need it, and the setting wont have any effect on the main LED. 😊
