### ISSUE TITLE
'class ATEMmin' has no member named 'getStreamStreaming'

### ISSUE THREAD

**Issue by sleyner** [AronHetLam/ATEM_tally_light_with_ESP8266#70]
Compilation error. 'class ATEMmin' has no member named 'getStreamStreaming' when loading ATEM_tally_light.ino. Which way to look?

**Comment by sleyner** [comment]
int getLedColor(int tallyMode, int tallyNo) {
  if (tallyMode == MODE_ON_AIR) {
    if (atemSwitcher.getStreamStreaming()) {
      return LED_RED;
    }
    return LED_OFF;
  }

**Comment by AronHetLam** [comment]
You got it working?
