### ISSUE TITLE
Led dimmer

### ISSUE THREAD

**Issue by jreckart** [AronHetLam/ATEM_tally_light_with_ESP8266#72]
Is it possible to add a dimming feature to the tally LED?
Sometimes in a dark room, the tally light is too bright, but in well lit rooms it's just right.
Perhaps add a control on the setup web page, to enter a value 0-100%. 
This would allow it to be changed depending on the situation.
Many thanks

**Comment by AronHetLam** [comment]
Take a look at release [v3.2.0](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/releases/tag/v3.2.0), and see if that does the trick. It has a few other changes is it as well, but they shouldn't break anything. Make sure to replace the libraries as well 😊
