### ISSUE TITLE
How to fix the blue LED error on esp8266

### ISSUE THREAD

**Issue by congminh3366** [AronHetLam/ATEM_tally_light_with_ESP8266#75]
hi admin and everyone, i'm having trouble setting up esp8266 for tally lights project. all lights on esp after "setup tally light" are green. Can anyone tell me how to fix it please?

**Comment by congminh3366** [comment]
![z3961286195437_c31710e3a9eb9e4e79aa6dd4a7917d29](https://user-images.githubusercontent.com/114283430/207818544-68ab1288-337d-4308-8ca8-8d98a8f72069.jpg)

**Comment by AronHetLam** [comment]
It's a little blurry, but it looks like you soldered the LEDs incorrectly. You have it soldered to `5v`, which is wrong. You should have the LED's Ground pin soldered to `G` instead.



Besides that, i have a hard time telling if the rest of the pins are soldered correctly. You could also try to connect a LEF without soldering it, to see if it's placed correctly. Then it's easier to change.

**Comment by congminh3366** [comment]
more precisely i used anode LED, i have reviewed the tally light setup process and it's true it's wrong there, now i only use green and red pins ( D2 , D0 ) What to do when the light is not working select it will not light anymore. Looking forward to your reply, thank you very much

**Comment by congminh3366** [comment]
![z3963219011870_9d9246517e5580c56119c34886a07570](https://user-images.githubusercontent.com/114283430/207993718-a14739c1-fc2c-4f8c-8e2e-6bed493b9158.jpg)
this is how i soldered the pins of the LED. Please tell me, are all 6 esp soldered like that or must be changed for each esp?

**Comment by congminh3366** [comment]
https://user-images.githubusercontent.com/114283430/207993952-0cb45c2f-b10a-4d58-b3e1-646be6bd282e.mp4
when the light is not selected, it is turned yellow, so it is difficult to see the change when selecting the tally light

**Comment by AronHetLam** [comment]
Ok, the wireing makes sense if you have common anode LEDs. However, the code must be changed for it to work.
The code pulls the pins high when their color should light up, but in your case it needs to be inverted, so that the pins are pulled low when their color should light up.

**Comment by congminh3366** [comment]
so now if i want it to turn off the light completely when not selected, where can i fix it, can you help me edit it?

**Comment by congminh3366** [comment]
can you give me the solution to fix that, thank you very much

**Comment by AronHetLam** [comment]
Yes, had to find it 😊 I also don't have a common anode LED, so I can't really test it properly.

But setting the colors all happens here:
https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/blob/master/ATEM_tally_light/ATEM_tally_light.ino#L425-L472

Try changing the `0`'s to `1`'s, and change the first line from `settings.ledBrightness` to `255 - settings.ledBrightness`

**Comment by congminh3366** [comment]
I can't find entries 0 and 1

**Comment by congminh3366** [comment]
can you remote support ultraview to change for me?

**Comment by AronHetLam** [comment]
Change each `0`(zero) to `1`(one) for each `digitalWrite(pinRed, 0);`. Eg. to `digitalWrite(pinRed, 1);`. 

Unfortunately I'm unable to remote.

**Comment by congminh3366** [comment]
oh great, i tried again and it worked. really thank you very much.

**Comment by congminh3366** [comment]
If there is a solution to alert the light when the signal is lost, I am sure it will be a great success that I have from you.

**Comment by AronHetLam** [comment]
Sorry for the late reply.
What do you mean by `alert the light`? The LED should turn pink if it loses connection to the ATEM and white if it loses connection to WiFi.

**Comment by congminh3366** [comment]
This is the result after following your instructions. How do you feel about
this product? Thank you for your interest in this product of mine. Below is
the product video link.
https://drive.google.com/file/d/152uBKgX5gSnybS2k7LHDN-5802UU6KYo/view?usp=sharing


Vào CN, 15 thg 1, 2023 vào lúc 21:41 Aron het Lam <
***@***.***> đã viết:

**Comment by AronHetLam** [comment]
Very nice end result! Thanks for sharing it 🙂
