### ISSUE TITLE
Neopixel not working correctly

### ISSUE THREAD

**Issue by Mikamuh** [AronHetLam/ATEM_tally_light_with_ESP8266#82]
Hi Everyone,

I am trying to get this to work using a NeoPixel-Stick. Somehow only the first LED is changing colors (not the correct ones though) but the remaining 7 LEDs are stuck.

I would love to get this to work but I don't know where to start searching for the solution.

![IMG_4867](https://user-images.githubusercontent.com/125920563/234855839-2a27ffe1-baa0-4aec-860d-925845739db3.JPG)
![IMG_4868](https://user-images.githubusercontent.com/125920563/234855853-0e31da1c-cea9-4b72-b799-08d228195b82.JPG)
![IMG_4869](https://user-images.githubusercontent.com/125920563/234855863-c0d736e8-8a36-4c37-b1aa-7db351320356.JPG)

**Comment by AronHetLam** [comment]
Try downgrading the board manager to the latest 2.x.x version, as version 3.x.x and higher started causing bronlems when using the FastLED library. Hope that makes sense 🙂

**Comment by Mikamuh** [comment]
Hi Aron,

thanks for the advice. I tried loading 2.1.1 onto the D1 Pro but when compiling I get faced with `Compilation error: redefinition of 'ESP8266WebServer server'`. 

Do you or anyone else have any input on how to proceed?

**Comment by AronHetLam** [comment]
That's a new one. Have you changed the code in any way, or are you using other libraries than the ones specified? Also, just to make sure, what board have you selected in the board manager?

**Comment by AronHetLam** [comment]
Wait, did you downgrade to my code to version 2.1.1, or the ESP8266 board manager in the Arduino IDE?
Make sure to use the latest version of my code, as it has the latest bugfixes and features, and downgrade the board manager to `2.7.4`:
![image](https://user-images.githubusercontent.com/5564813/235124513-f1e0ca40-aa43-497f-a14c-88a65c8a257f.png)

**Comment by AronHetLam** [comment]
I have now updated the guide so it specifies to use version the ESP8266 board manager version 2.7.4 :)

**Comment by Mikamuh** [comment]
That did the Trick. Everything is working as expected now!
Thank you so much :)

**Comment by dmitrylive** [comment]
I have a similar problem! I'm having trouble using the Arduino software. I started using the web version, it's very cool, thanks for this opportunity! I bought the boards as written in the description, D1 mini and D1 mini pro. D1 mini works correctly, I checked several boards. And on the D1 mini pro (with an external antenna) the neopixel works the same way as in the screenshots above. I tried installing different numbers of LEDs - the first one works as it should, and the rest periodically change color. frequency is unclear. I would like to use the board with an external antenna. I just can’t figure out if my board is faulty or if the mini pro has the same problem?

**Comment by AronHetLam** [comment]
I made issue #94, which addresses the Arduino IDE problem.
The same [branch](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/tree/fixArduinoIdeCompatabillity) mentioned there hopefully fixes the neopixel problem for the web installer too. It didn't use the older ESP8266 board versions, with that code it should.

@dmitrylive can I have you try it out on the D1 mini pro through the Arduino IDE to see if the Neopixels work correctly with boards manager version `2.7.4`?
