### ISSUE TITLE
Dip switch for change tally channel

### ISSUE THREAD

**Issue by dmitrylive** [AronHetLam/ATEM_tally_light_with_ESP8266#84]
Hello! Thanks for this guide, everything turned out to be done, although not the first time. I have a suggestion, I do not know where to write. It would be cool to implement the ability to change the channel using a dip switch. 3 buttons are enough for 8 channels 

(000, 001, 010, 011, 100, 101, 110, 111). 

![3-position-dip-switch](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/96445359/46a80e5f-2056-4ae2-9e44-b9d3aab0631b)

This board also has free channels.

Unfortunately, I am very far from programming, I am a sound engineer ... with a passion for media engineering) This will speed up the replacement process a little if one tally suddenly breaks or runs out of power. You will not need to open the web interface, the switches are set up faster)  

I think a lot of people will be interested.

Thanks for your work!

**Comment by AronHetLam** [comment]
Hi, I'm glad to hear you got it working, and thanks for the suggestion. 

However, you're not the first to suggest this. Take a look at my answer here: https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/issues/37#issuecomment-874197403

In short, some switchers have up to 41 inputs as far as i remember, so a dip-switch solution isn't sufficient. In that other issue there is a link to a version that allows scrolling through tally the numbers with a button, but there's no knowing what channel you're at. And also the updated channel isn't saved..

I'll close this issue as it's a duplicate. Please feel free to put your thoughts in the existing issue #37. If the button solution works for you I could polish it (at least make it save...), and put it in a release. :)
