### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by commputethis** [AronHetLam/ATEM_tally_light_with_ESP8266#85]
Is it possible to test these devices without an ATEM being available?  We are working on setting these up for our church, but don't have ATEM at home where we are building them.  I see there is a ATEM_tally_test_server sketch and see it was mentioned in another issue that it is used for testing, but we aren't sure how to use it.

**Comment by AronHetLam** [comment]
Yes it is.
If you upload the `ATEM_tally_test_server` program to one of your tally lights, you can use it as a fake switcher. Once uploaded, open up the serial monitor in the Arduino IDE (top right corner), select `115200 baud`, and you should be able to switch between the following states by pressing enter.
- live
- preview
- live + priview
- none

For other tally lights, just use the test server tally's  IP-address as switcher IP.
