### ISSUE TITLE
Compling issue

### ISSUE THREAD

**Issue by KauppaKumpu** [AronHetLam/ATEM_tally_light_with_ESP8266#90]
I'm totally out my comforzone here as building Tally Lights as instructed. 

Followed instructions step by step. Got stuff downloaded and installed unzipped stuff to Arduino directory as instructed but: on bot tested computers. iMac running OS 13.5.1 and Win10 same thing: 

Compling stops on both systems to  a error: Copypasting error here: 

" .../Arduino/ATEM_tally_light_with_ESP8266-3.2.1/ATEM_tally_light/ATEM_tally_light.ino:35:10: fatal error: ATEMmin.h: No such file or directory
   35 | #include <ATEMmin.h>
      |          ^~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: ATEMmin.h: No such file or directory"

Have not a slightest clue where things went wrong since could duplicate this on two separate systems. Just to be sure used another USB cable and problem didn't go away.

**Comment by AronHetLam** [comment]
It seems like you haven't copied the libraries into the correct folder, as it's unable to find `ATEMmin.h`.
From the error message it looks like you extracted the downloaded zip-file into the `.../Arduino` folder. This isn't necessarily a problem, but you need to copy the folders inside `libraries` from the download into `.../Arduino/libraries`. This is where the Arduino IDE looks for libraries.

I hope that makes sense. 🙂

**Comment by KauppaKumpu** [comment]
Well my directory looks like this on iMac, same on Win machine


<img width="716" alt="Näyttökuva 2023-9-5 kello 19 39 38" src="https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/144147644/97908a54-1edb-4d57-9047-492526272940">

**Comment by AronHetLam** [comment]
You need to move the `libraries` folder into the `.../Arduino` folder - so one step up in the hierarchy. The rest is all fine.

**Comment by KauppaKumpu** [comment]
Thanks! Will test right away.

**Comment by KauppaKumpu** [comment]
Should be ok, but no go still  - time to call it a day

<img width="687" alt="Näyttökuva 2023-9-5 kello 20 03 43" src="https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/144147644/70476802-d08b-4b07-af22-ea1c19a9ea1d">

**Comment by AronHetLam** [comment]
Still doesn't look quite right. You need to move the `libraries` so that it is directly inside the `Arduino` folder.

Currently you have:
```
Arduino
-- ATEM_tally_light_with_ESP8266-3.2.1
---- libraries
------ ...
```

But you need to  have:
```
Arduino
-- ATEM_tally_light_with_ESP8266-3.2.1
---- ...
-- libraries
---- ...
```

**Comment by KauppaKumpu** [comment]
Ok new day new ideas: Swapped to web version of Arduino IDE just to remove software/computer issues from equation, did fresh download from project page, -zip format as it offers. Upload downloaded .zip packet unaltered to Arduino web service and hook up project board as per instructions. All seems fine so far.

Hitting Verify introduces errors and process stops: 

"..parse library properties: library properties not found.." 

Defining missing these libraries: TallyServer, ATEMBbase and ATEMmin

Now totally out of ideas how to as packet uploaded to service is same as downloaded from GitHub project page it so problem is no more on my end of the internet. Need these tallys made and running within week. So please help!

**Comment by AronHetLam** [comment]
This is what my libraries folder looks like. There's a lot of other stuff that you don't need, but that I use in other projects, so you can ignore those. The ones underlined with red are the ones you download with my code, and the `FastLED` (orange line) is one you add through the library manager, as described in the guide. 
![image](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/5564813/0c67f4ee-9363-4ec0-993e-d769f266a1ea)

**Comment by KauppaKumpu** [comment]
I used web version just to rule out bunch of possible problems and it has better overdosing of errors - lots of first time things happening here.

But due my old eyes.. can't see a properly all details of that screenshot on laptop but thin red lines on yellow something gibberish on a black background. Not on my desktop for rest of the day so can't verify my filestructure for sure till tomorrow but seems like to be same.

Let me verbose my thoughts right now before leaving house for rest of the day:

As I download latest .zip packet from GitHub it should contain *all* necessary files on *right* folders meaning file structure works on me too despite different operation systems used?  

This is what I've come to understand after reading instructions. 

That far I can also understand there should be no chances for mishappenings of my actions as I'm not doing nor able of doing a thing to alter it 

Then unzipping it to a folder of my choice should recreate this correct structure. 

As far as I still can understand  I can't mess things up as my only action after downloading .zip packet is to hit unzip and let it happen while taking zip of my coffee.

Then launching Arduino IDE and opening freshly unzipped  .ino file on it should survive the compile task like it supposed to and upload needed pieces of zeros and ones to ESP unit and tally lights work after setup?

If I only had savvy tech oriented friends nearby who could help with this, but no hope on that. It is beyond their skills too. They tend to think most of my stuff being odd wizardy already.

Thanks for Your patience.

**Comment by AronHetLam** [comment]
> As I download latest .zip packet from GitHub it should contain _all_ necessary files on _right_ folders meaning file structure works on me too despite different operation systems used?

This is not correct.
The Arduino IDE requires that you to __move__ the library folders into the specific `.../Arduino/libraries` folder. This is the __only__ place the Arduino IDE looks for libraries. 
This is also where the Arduino IDE will put the `FastLED` library when you add it through the library manager (which is described in the guide as well). If you add the `FastLED` library first, you will see `.../Arduino/libraries/FaseLED` be created.

This is what you have, which will __not__ work:
`C:/Users/USERNAME/Arduino/ATEM_tally_light_with_ESP8266-3.2.1/libraries/ATEMbase`
``C:/Users/USERNAME/Arduino/ATEM_tally_light_with_ESP8266-3.2.1/libraries/ATEMmin`
`C:/Users/USERNAME/Arduino/ATEM_tally_light_with_ESP8266-3.2.1/libraries/SkaarhojPgmspace`
`C:/Users/USERNAME/Arduino/ATEM_tally_light_with_ESP8266-3.2.1/libraries/TallyServer`

This is what it needs to look like:
`C:/Users/USERNAME/Arduino/libraries/ATEMbase`
`C:/Users/USERNAME/Arduino/libraries/ATEMmin`
`C:/Users/USERNAME/Arduino/libraries/SkaarhojPgmspace`
`C:/Users/USERNAME/Arduino/libraries/TallyServer`

However, it doesn't matter where the `ATEM_tally_light.ino` file is.

Here is the important part of the image, which should make it bigger: 
![image](https://github.com/AronHetLam/ATEM_tally_light_with_ESP8266/assets/5564813/a886e28d-40bf-4161-8c4a-52c339a64f81)
