### ISSUE TITLE
Question About Built-in LED

### ISSUE THREAD

**Issue by DonaldPotbury** [AronHetLam/ATEM_tally_light_with_ESP8266#91]
Hello, Thanks for this awesome system.  It's working great!

One thing I've noticed is the Built-in LED.  When in "program" it is dark.  All other states it seems to be lit.
I'm having trouble finding where to control that.  Can you point me in the right direction?

We are using the ESP8266 Mini.

Thanks in advance.

**Comment by AronHetLam** [comment]
You're welcome. 🙂

The built-in LED on the D1 mini is connected to the same pin as the red color, but inverted. This is why it behaves like it does. I don't remember if it's the red pin for the first or second LED, but that should be easy to Google for.
